server:
  port: 8889
spring:
  application:
    name: zuul
  zipkin:
    base-url: http://localhost:9092
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/,http://localhost:8002/eureka/
      defaultZone: http://localhost:8761/eureka/